name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      # Build your program with the given configuration
      run:  |
        mkdir -p build
        cd build
        cmake ..
        make
        mkdir -p release
        cp -r lib/ examples/ ../headers/threadcontroller.h release
        uses: actions/upload-artifact@v3
        with:
        # Artifact name
        name: v0.0.1
        # Destination path
        path: /home/runner/work/thread-control/thread-control/build/release
